# Manifest file for catalogue

# This created ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cart
  namespace: Ecomm-01
data: 
  REDIS_HOST: "cart"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
# This creates Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-cart
  namespace: Ecomm-01
  labels:
    app: cart
    project: Ecomm
    tier: Api-tier
spec:
  replicaSet: 1
  selector:
    MatchLabels:
      app: cart
      project: Ecomm
      tier: Api-tier  
  template:
    metadata:
      Labels:
        app: cart
        project: Ecomm
        tier: Api-tier 
    spec:
      containers:
      - name: cart
        image: naveenallam/cart:v1
        imagePullPolicy: Always
        resources:
          requests:
          limits:  
        envFrom: 
        - ConfigMapRef:
            name: configMapforENV # It will take ENV from mentioned file name.
---
# This creates ClusterIp for communication in the Deployment
apiVersion: v1
kind: service
metadata:
  name: clusterIP-cart
  namespace: Ecomm-01
spec:
  selector:
    app: cart
    project: Ecomm
    tier: Api-tier
  ports:
  - protocol: TCP
    port: 8080 # servicePort
    targetPort: 8080 # ContainerPort

      
                
             
              
                  