# Manifest file for catalogue

# This created ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: user
  namespace: Ecomm-01
data:
  MONGO: "true"
---
# This creates Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-user
  namespace: Ecomm-01
  labels:
    app: user
    project: Ecomm
    tier: Api-tier
spec:
  replicaSet: 1
  selector:
    MatchLabels:
      app: user
      project: Ecomm
      tier: Api-tier  
  template:
    metadata:
      Labels:
        app: user
        project: Ecomm
        tier: Api-tier 
    spec:
      containers:
      - name: user
        image: naveenallam/user:v1
        imagePullPolicy: Always
        resources:
          requests:
          limits:  
        envFrom: 
        - ConfigMapRef:
            name: configMapforENV # It will take ENV from mentioned file name.
---
# This creates ClusterIp for communication in the Deployment
apiVersion: v1
kind: service
metadata:
  name: clusterIP-user
  namespace: Ecomm-01
spec:
  selector:
    app: user
    project: Ecomm
    tier: Api-tier
  ports:
  - protocol: TCP
    port: 8080 # servicePort
    targetPort: 8080 # ContainerPort

      
                
             
              
                  